"use server";

import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
}

export default async function RootLayout({ children }: PropsWithChildren) {
  return <>{children}</>;
}
